const jobs = [
  {
    position: "Software Engineer",
    company: "TechCorp",
    jobLocation: "San Francisco",
    status: "interview",
    jobType: "full-time",
    id: 1,
  },
  {
    position: "Product Manager",
    company: "InnovateX",
    jobLocation: "New York",
    status: "pending",
    jobType: "full-time",
    id: 2,
  },
  {
    position: "Data Scientist",
    company: "DataGen",
    jobLocation: "Chicago",
    status: "declined",
    jobType: "full-time",
    id: 3,
  },
  {
    position: "Marketing Specialist",
    company: "MarketMakers",
    jobLocation: "Los Angeles",
    status: "pending",
    jobType: "part-time",
    id: 4,
  },
  {
    position: "UX Designer",
    company: "DesignHub",
    jobLocation: "Austin",
    status: "interview",
    jobType: "full-time",
    id: 5,
  },
  {
    position: "Sales Representative",
    company: "SalesForce",
    jobLocation: "Seattle",
    status: "interview",
    jobType: "remote",
    id: 6,
  },
  {
    position: "HR Manager",
    company: "PeopleFirst",
    jobLocation: "Miami",
    status: "pending",
    jobType: "full-time",
    id: 7,
  },
  {
    position: "Business Analyst",
    company: "BizAnalyzers",
    jobLocation: "Denver",
    status: "declined",
    jobType: "full-time",
    id: 8,
  },
  {
    position: "Network Engineer",
    company: "NetConnect",
    jobLocation: "San Diego",
    status: "pending",
    jobType: "full-time",
    id: 9,
  },
  {
    position: "Graphic Designer",
    company: "CreativeWorks",
    jobLocation: "Portland",
    status: "interview",
    jobType: "part-time",
    id: 10,
  },
  {
    position: "Customer Support",
    company: "HelpDesk",
    jobLocation: "Las Vegas",
    status: "pending",
    jobType: "full-time",
    id: 11,
  },
  {
    position: "Web Developer",
    company: "WebSolutions",
    jobLocation: "Phoenix",
    status: "interview",
    jobType: "full-time",
    id: 12,
  },
  {
    position: "Operations Manager",
    company: "EfficientOps",
    jobLocation: "Dallas",
    status: "declined",
    jobType: "full-time",
    id: 13,
  },
  {
    position: "Mobile Developer",
    company: "AppCreators",
    jobLocation: "San Jose",
    status: "interview",
    jobType: "remote",
    id: 14,
  },
  {
    position: "Financial Analyst",
    company: "FinInsights",
    jobLocation: "Houston",
    status: "pending",
    jobType: "full-time",
    id: 15,
  },
  {
    position: "Social Media Manager",
    company: "Socialize",
    jobLocation: "Atlanta",
    status: "interview",
    jobType: "part-time",
    id: 16,
  },
  {
    position: "Content Writer",
    company: "WriteNow",
    jobLocation: "Boston",
    status: "pending",
    jobType: "full-time",
    id: 17,
  },
  {
    position: "IT Support",
    company: "TechHelp",
    jobLocation: "Detroit",
    status: "declined",
    jobType: "full-time",
    id: 18,
  },
  {
    position: "Cybersecurity Specialist",
    company: "SecureNet",
    jobLocation: "Philadelphia",
    status: "interview",
    jobType: "full-time",
    id: 19,
  },
  {
    position: "Recruiter",
    company: "HireTalent",
    jobLocation: "Baltimore",
    status: "pending",
    jobType: "full-time",
    id: 20,
  },
  {
    position: "Quality Assurance",
    company: "QATech",
    jobLocation: "Charlotte",
    status: "declined",
    jobType: "full-time",
    id: 21,
  },
  {
    position: "Project Manager",
    company: "ManageIt",
    jobLocation: "Minneapolis",
    status: "pending",
    jobType: "full-time",
    id: 22,
  },
  {
    position: "DevOps Engineer",
    company: "CloudOps",
    jobLocation: "San Antonio",
    status: "interview",
    jobType: "remote",
    id: 23,
  },
  {
    position: "Electrical Engineer",
    company: "ElectroWorks",
    jobLocation: "Orlando",
    status: "declined",
    jobType: "full-time",
    id: 24,
  },
  {
    position: "SEO Specialist",
    company: "SearchMax",
    jobLocation: "Indianapolis",
    status: "interview",
    jobType: "part-time",
    id: 25,
  },
];

export default jobs;
